using CoworkingBooking.Core.Workspace.Enums;
using CoworkingBooking.Shared.Classes;

namespace CoworkingBooking.Core.Workspace.Entities
{
    public class WorkspaceEntity
    {
        public string Id { get; private set; } = string.Empty;
        public string Name { get; private set; } = string.Empty;
        public string Description { get; private set; } = string.Empty;
        public string Slug { get; private set; } = string.Empty;
        public WorkspaceType Type { get; private set; }
        public WorkspaceStatus Status { get; private set; }
        public GeoJson Coordinates { get; private set; }
        public double PricePerHour { get; private set; }
        public bool IsInactive { get; private set; }
        public IReadOnlyList<string> Resources { get; private set; } = Array.Empty<string>();
        private List<string> _resources = new List<string>();
        public WorkSpaceAvailability? Availability { get; private set; }
        private WorkSpaceAvailability? _availability;
        public DateTime CreatedAt { get; private set; } = default;
        public DateTime UpdatedAt { get; private set; } = default;
        
        public WorkspaceEntity(
            string name,
            string description,
            WorkspaceType type,
            GeoJson coordinates,
            double pricePerHour,
            IReadOnlyList<string> resources
        )
        {
            this.Id = string.Empty; // Id will be generated by the database upon insertion
            this.Name = NormalizeRequired(name, nameof(name));
            this.Description = NormalizeRequired(description, nameof(description));
            this.Type = ValidateWorkspaceType(type);
            this.Coordinates = ValidateCoordinates(coordinates);
            this.PricePerHour = ValidatePricePerHour(pricePerHour);
            this.Resources = NormalizeResources(resources);
            this._resources = this.Resources.ToList();
            this.CreatedAt = DateTime.UtcNow.ToUniversalTime();
            this.UpdatedAt = DateTime.UtcNow.ToUniversalTime();

            this.Status = WorkspaceStatus.Draft; // Default status
            this.IsInactive = false; // Default to active
        }

        public static WorkspaceEntity Rehydrate(
            string id,
            string name,
            string description,
            string slug,
            WorkspaceType type,
            WorkspaceStatus status,
            GeoJson coordinates,
            double pricePerHour,
            bool isInactive,
            IReadOnlyList<string> resources,
            DateTime createdAt,
            DateTime updatedAt,
            WorkSpaceAvailability? availability
        )
        {
            var entity = new WorkspaceEntity(name, description, type, coordinates, pricePerHour, resources)
            {
                Id = NormalizeId(id),
                Slug = NormalizeRequired(slug, nameof(slug)),
                Status = ValidateWorkspaceStatus(status),
                IsInactive = isInactive,
                CreatedAt = ValidateCreatedAt(createdAt, updatedAt),
                UpdatedAt = ValidateUpdatedAt(updatedAt, createdAt),
                Availability = availability,
                _availability = availability
            };

            return entity;
        }

        public void Publish(string generatedSlug)
        {
            this.Slug = NormalizeRequired(generatedSlug, nameof(generatedSlug));
            this.Status = WorkspaceStatus.Draft; // Set status to Draft when publishing
            this.IsInactive = false;
        }

        public void Activate()
        {
            this.IsInactive = false;
        }

        public void Deactivate()
        {
            this.IsInactive = true;
        }

        public void MarkAsReserved()
        {
            this.Status = WorkspaceStatus.Reserved;
        }

        public void MarkUnderMaintenance()
        {
            this.Status = WorkspaceStatus.Maintenance;
        }

        public void MarkAsUnavailable()
        {
            this.Status = WorkspaceStatus.Unavailable;
        }

        public void UpdateStatus(WorkspaceStatus status)
        {

            ArgumentNullException.ThrowIfNull(status.ToString(), nameof(status));

            if (status == WorkspaceStatus.Available)
            {
                if (this._availability == null)
                {
                    throw new InvalidOperationException($"Workspace cannot update status to {status.ToString()} because Availability is not set.");
                }
            }
            else if (status == WorkspaceStatus.Maintenance)
            {
                // if (this.HasBooking())
                // {
                //     throw new InvalidOperationException($"Worspace cannot update status to {status.ToString()} because has Booking.");
                // }
            }
            // else if (status == WorkspaceStatus.Unavailable)
            // {
                
            // }

            this.Status = status;
        }

        public void UpdateAvailability(WorkSpaceAvailability availability)
        {
            ArgumentNullException.ThrowIfNull(availability, nameof(availability));

            // if (this.HasBooking())
            // {
            //     throw new InvalidOperationException($"Cannot update availability because there are existing unavailable slots.");   
            // }

            this._availability = availability;
            this.Availability = availability;
        }

        public void RemoveResource(string resource)
        {
            ArgumentNullException.ThrowIfNullOrWhiteSpace(resource, nameof(resource));

            var trimmedResource = resource.Trim();
            if (_resources.Contains(trimmedResource))
            {
                _resources.Remove(trimmedResource);
                Resources = _resources.AsReadOnly();
            }
        }

        public void AddResource(string resource)
        {
            ArgumentNullException.ThrowIfNullOrWhiteSpace(resource, nameof(resource));

            var trimmedResource = resource.Trim();
            if (!_resources.Contains(trimmedResource))
            {
                _resources.Add(trimmedResource);
                Resources = _resources.AsReadOnly();
            }
        }

        // private bool HasBooking()
        // {
        //     if (this._dayOfWeekAvailables.Count > 0)
        //     {
        //         foreach(var availability in this._dayOfWeekAvailables)
        //         {
        //             if(availability.IsAvailable.HasValue && availability.IsAvailable.Value == false)
        //             {
        //                 return true;
        //             }
        //         }

        //         return false;
        //     }

        //     return false;
        // }

        private static string NormalizeId(string id)
        {
            ArgumentNullException.ThrowIfNullOrWhiteSpace(id, nameof(id));

            return id.Trim();
        }

        private static string NormalizeRequired(string value, string propertyName)
        {
            return string.IsNullOrWhiteSpace(value)
                ? throw new ArgumentException($"{propertyName} is required.", propertyName)
                : value.Trim();
        }

        private static string NormalizeOptional(string value)
        {
            return string.IsNullOrWhiteSpace(value) ? string.Empty : value.Trim();
        }

        private static DateTime NormalizeDate(DateTime value)
        {
            return value.ToUniversalTime();
        }

        private static WorkspaceType ValidateWorkspaceType(WorkspaceType value)
        {
            return Enum.IsDefined(typeof(WorkspaceType), value)
                ? value
                : throw new ArgumentOutOfRangeException(nameof(value), "Invalid workspace type.");
        }

        private static WorkspaceStatus ValidateWorkspaceStatus(WorkspaceStatus value)
        {
            return Enum.IsDefined(typeof(WorkspaceStatus), value)
                ? value
                : throw new ArgumentOutOfRangeException(nameof(value), "Invalid workspace status.");
        }

        private static GeoJson ValidateCoordinates(GeoJson value)
        {
            ArgumentNullException.ThrowIfNull(value);

            if (value.coordinates is null || value.coordinates.Length != 2)
            {
                throw new ArgumentException("coordinates must contain [longitude, latitude].", nameof(value));
            }

            var longitude = value.coordinates[0];
            var latitude = value.coordinates[1];
            if (longitude is < -180 or > 180 || latitude is < -90 or > 90)
            {
                throw new ArgumentOutOfRangeException(nameof(value), "Invalid longitude/latitude values.");
            }

            return value;
        }

        private static double ValidatePricePerHour(double value)
        {
            return value < 0
                ? throw new ArgumentOutOfRangeException(nameof(value), "pricePerHour cannot be negative.")
                : value;
        }

        private static IReadOnlyList<string> NormalizeResources(IReadOnlyList<string> value)
        {
            ArgumentNullException.ThrowIfNull(value);
            if (value.Any(string.IsNullOrWhiteSpace))
            {
                throw new ArgumentException("resources cannot contain empty items.", nameof(value));
            }

            return value.Select(resource => resource.Trim()).ToList().AsReadOnly();
        }

        private static DateTime ValidateCreatedAt(DateTime createdAt, DateTime updatedAt)
        {
            if (createdAt > updatedAt)
            {
                throw new ArgumentException("createdAt cannot be greater than updatedAt.", nameof(createdAt));
            }

            return NormalizeDate(createdAt);
        }

        private static DateTime ValidateUpdatedAt(DateTime updatedAt, DateTime createdAt)
        {
            if (updatedAt < createdAt)
            {
                throw new ArgumentException("updatedAt cannot be less than createdAt.", nameof(updatedAt));
            }

            return NormalizeDate(updatedAt);
        }

        private static IReadOnlyList<WorkSpaceAvailability> NormalizeAvailabilities(IReadOnlyList<WorkSpaceAvailability> value)
        {
            ArgumentNullException.ThrowIfNull(value);
            return value;
        }
    
    }
}