appendonly yes

user default off

user api on >Kx#mP9$vL2@nQ4rT7uW5yZ8aB3cD6eF1 ~* +@all
user worker on >J4$bN2#vK8@mL5pR9sT6uW3yX7zA1cD4 ~* +@all
user hangfire on >V8@cP3$nQ7#tR2uW9sL5yX4aZ1bD6eF8 ~* +@all
user admin on >M6#xK1$vL9@pR4nT8uW2yZ5aB3cD7eF0 ~* +@all
